### PR TITLE
4094 o+c set preferred name

### PR DESCRIPTION
**Pull request by NicholasDom**
Added set-preferred-name test

### CODE REVIEW

**Review by pat-ryan-health — APPROVED** [review]
lovely

**Comment by NicholasDom** [comment]
Merged - could you please do a build

**Comment by pat-ryan-health** [comment]
New build here:
https://master.d3b08qop7whnnl.amplifyapp.com/

**Comment by pat-ryan-health** [comment]
I don’t think that worked I will try again

From: Pat Ryan
Sent: Wednesday, 11 January 2023 11:43 am
To: HL7NZ/nhi ***@***.***>
Subject: RE: [HL7NZ/nhi] 4094 o+c set preferred name (PR #41)

New build here:
https://master.d3b08qop7whnnl.amplifyapp.com/

**Comment by NicholasDom** [comment]
I was just in the process of messaging you :)

**Pull request merged**
