### PR TITLE
Gp

### PR DESCRIPTION
**Pull request by pat-ryan-health**

### CODE REVIEW

**Review by NicholasDom — APPROVED** [review]
Looks good in here

**Review by NicholasDom — APPROVED** [review]
Looks good in here

**Review by daniel-thomson — APPROVED** [review]

**Review by daniel-thomson — APPROVED** [review]
Would we ever want people to derive profiles from the NHI? If they did, they may want contained resources for things like contacts, managing org etc.  I'm not 100% sure but I think closing the slicing here would preclude that.

Easy to change (and prob without impact) if needed though

**Comment by pat-ryan-health** [comment]
Good point, but I would expect people to derive from NzBase rather than NHI

**Pull request merged**
